version: '3'

services:
  cezerin2:
    image: cezerin2/cezerin2
    environment:
      - LANGUAGE=ru
    ports:
      - 3001:80
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shop
      - DB_USER=
      - DB_PASS=
    volumes:
      - ./content-on-host:/var/www/cezerin2/public/content
    depends_on:
      - db
    restart: always

  cezerin2-store:
    image: cezerin2/cezerin2-store
    environment:
      - LANGUAGE=ru
      - API_BASE_URL=http://cezerin2/api/v1
      - AJAX_BASE_URL=http://cezerin2/ajax
    volumes:
      - ./content-scss:/var/www/cezerin/theme/assets/scss
      - ./content-sass:/var/www/cezerin/theme/assets/sass
      - ./content-src:/var/www/cezerin/theme/src
      - ./content-settings:/var/www/cezerin/theme/settings
      - ./content-locales:/var/www/cezerin/theme/locales
    ports:
      - 3000:80
    depends_on:
      - cezerin2
    restart: always

  admin:
    image: cezerin2/cezerin2-admin
    environment:
      - LANGUAGE=ru
    ports:
      - 3002:80
    depends_on:
      - cezerin2
    restart: always

  db:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./db-on-host:/data/db
    restart: always